# Generated by Django 4.0.6 on 2022-08-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeJi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('href', models.CharField(max_length=256, verbose_name='视频链接')),
                ('created', models.CharField(max_length=32, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='UpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=16, verbose_name='视频主id号')),
                ('name', models.CharField(max_length=32, verbose_name='up主')),
            ],
        ),
        migrations.CreateModel(
            name='UpVideoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('href', models.CharField(max_length=256, verbose_name='视频链接')),
                ('created', models.CharField(max_length=32, verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='账号名')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('href', models.CharField(max_length=256, verbose_name='视频链接')),
                ('created', models.CharField(max_length=32, verbose_name='发布时间')),
                ('status', models.SmallIntegerField(choices=[(0, '未看'), (1, '已看')], verbose_name='是否观看')),
            ],
        ),
        migrations.CreateModel(
            name='AjaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('math', models.IntegerField(verbose_name='数学成绩')),
                ('english', models.IntegerField(verbose_name='英语成绩')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.upinfo', verbose_name='up主')),
            ],
        ),
    ]
